- name: install packages from repository
  sudo: true
  apt: pkg={{ item }}
  with_items:
    - vim
    - screen
    - git-core
    - ack-grep
    - htop
    - curl
    - wget
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: get bash_it
  git: repo=https://github.com/Bash-it/bash-it.git dest=~/.bash_it depth=1

- name: get vundle
  git: repo=https://github.com/VundleVim/Vundle.vim.git dest=~/.vim/bundle/Vundle.vim

- name: get rbenv
  git: repo=https://github.com/sstephenson/rbenv.git dest=~/.rbenv

- name: get ruby-build
  git: repo=https://github.com/sstephenson/ruby-build.git dest=~/.rbenv/plugins/ruby-build

- name: get rbenv-aliases
  git: repo=https://github.com/tpope/rbenv-aliases.git dest=~/.rbenv/plugins/rbenv-aliases

- name: copy vimrc
  copy: src='vimrc' dest='~/.vimrc'

- name: copy screenrc
  copy: src='screenrc' dest='~/.screenrc'

- name: copy bashrc
  copy: src='bashrc' dest='~/.bashrc'

- name: install vim bundle
  command: /usr/bin/vim +BundleInstall +quitall
